name: 'Sync from the Remote repo action'
description: 'Allows to keep a separate shallow repo with the code from the remote repo'
author: 'Alex Antonyuk'

inputs:
  source:
    required: true
    description: 'Source repo'
  exclude:
    required: true
    description: 'List of excluded items from sync'

runs:
  using: node20
  main: dist/index.js
